spring:
  datasource:
    url: jdbc:mysql://localhost:3310/patient_service
    username: patient
    password: Secure@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8010