server:
  port: ${CONFIG_SERVER_PORT}
spring:
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_GIT_BRANCH}
          uri: ${CONFIG_GIT_URI}
          search-paths: config-data
  application:
    name: config-server